ci: ubuntu-latest

diff --git a/.github/workflows/test-seq.yaml b/.github/workflows/test-seq.yaml
--- a/.github/workflows/test-seq.yaml
+++ b/.github/workflows/test-seq.yaml
@@ -8,9 +8,7 @@ on:
 jobs:
   release-please:
     name: Release Please
-    runs-on:
-      - self-hosted
-      - general
+    runs-on: ubuntu-latest
     steps:
       - name: Release Please
         uses: google-github-actions/release-please-action@v3
@@ -19,42 +17,41 @@ jobs:
           release-type: simple
     outputs:
       release-created: ${{ steps.release-please.outputs.release_created }}
-      tag-name: ${{ steps.release-please.outputs.tag_name || 'master' }}
-
-  deploy-test:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Run Database Migration
-        if: ${{ '1' == '2' }}
-        id: db-migration
-        run: |
-          echo "migrationState=Deployed" >> $GITHUB_OUTPUT
-          echo "failureMessage='Migration failed'" >> $GITHUB_OUTPUT
-
-      - name: ECS deploy
-        if: steps.db-migration.outcome == 'skipped' || steps.db-migration.outputs.migrationState == 'Deployed'
-        id: ecs-deploy
-        run: |
-          echo "deploymentState=Failure" >> $GITHUB_OUTPUT
-          echo "failureMessage='Deployment failed'" >> $GITHUB_OUTPUT
-
-      - name: Detecting failure
-        if: steps.ecs-deploy.outputs.deploymentState == 'Failure' || steps.db-migration.outputs.migrationState == 'Failure'
-        run: |
-          echo "Failures while updating services"
-          exit 1
-
-    outputs:
-      deployment-state: ${{ steps.ecs-deploy.outputs.deploymentState || steps.db-migration.outputs.migrationState }}
-      failure-message: ${{ steps.db-migration.outputs.failureMessage || steps.db-migration.outputs.failureMessage }}
-
-  output-test:
-    if: always()
-    runs-on: ubuntu-latest
-    needs:
-      - deploy-test
-    steps:
-      - name: echo
-        run: |
-          echo "${{ needs.deploy-test.outputs.deployment-state }}"
-          echo "${{ needs.deploy-test.outputs.failure-message }}"
+      tag-name: ${{ steps.release-please.outputs.tag_name || 'main' }}
+  # deploy-test:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Run Database Migration
+  #       if: ${{ '1' == '2' }}
+  #       id: db-migration
+  #       run: |
+  #         echo "migrationState=Deployed" >> $GITHUB_OUTPUT
+  #         echo "failureMessage='Migration failed'" >> $GITHUB_OUTPUT
+  #
+  #     - name: ECS deploy
+  #       if: steps.db-migration.outcome == 'skipped' || steps.db-migration.outputs.migrationState == 'Deployed'
+  #       id: ecs-deploy
+  #       run: |
+  #         echo "deploymentState=Failure" >> $GITHUB_OUTPUT
+  #         echo "failureMessage='Deployment failed'" >> $GITHUB_OUTPUT
+  #
+  #     - name: Detecting failure
+  #       if: steps.ecs-deploy.outputs.deploymentState == 'Failure' || steps.db-migration.outputs.migrationState == 'Failure'
+  #       run: |
+  #         echo "Failures while updating services"
+  #         exit 1
+  #
+  #   outputs:
+  #     deployment-state: ${{ steps.ecs-deploy.outputs.deploymentState || steps.db-migration.outputs.migrationState }}
+  #     failure-message: ${{ steps.db-migration.outputs.failureMessage || steps.db-migration.outputs.failureMessage }}
+  #
+  # output-test:
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - deploy-test
+  #   steps:
+  #     - name: echo
+  #       run: |
+  #         echo "${{ needs.deploy-test.outputs.deployment-state }}"
+  #         echo "${{ needs.deploy-test.outputs.failure-message }}"
